# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext

    role_hierarchy:
        ROLE_USER:
        ROLE_MODERATOR:       [ROLE_USER, ROLE_MODERATOR]        
        ROLE_ADMIN:       [ROLE_USER, ROLE_MODERATOR, ROLE_ADMIN]


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/ 
            form_login: 
                provider: fos_userbundle 
                csrf_provider: form.csrf_provider 
                login_path: /login
                check_path: /login_check
                always_use_default_target_path: false
                default_target_path: /home_page
            logout:
                path: /logout
                target: /login
            anonymous:    true 

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/categorie/, role: ROLE_ADMIN }
    access_decision_manager:
        strategy: unanimous