admin_type_index:
    path:     /index
    defaults: { _controller: "OrionEventBundle:Admin_Type:index" }

admin_type_show:
    path:     /{id}/show
    defaults: { _controller: "OrionEventBundle:Admin_Type:show" }

admin_type_new:
    path:     /new
    defaults: { _controller: "OrionEventBundle:Admin_Type:new" }

admin_type_create:
    path:     /create
    defaults: { _controller: "OrionEventBundle:Admin_Type:create" }
    methods:  POST

admin_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "OrionEventBundle:Admin_Type:edit" }

admin_type_update:
    path:     /{id}/update
    defaults: { _controller: "OrionEventBundle:Admin_Type:update" }
    methods:  [POST, PUT]

admin_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "OrionEventBundle:Admin_Type:delete" }
    methods:  [POST, DELETE]

admin_type_activate:
    path:     /{id}/activate
    defaults: { _controller: "OrionEventBundle:Admin_Type:activate" }

admin_type_deactivate:
    path:     /{id}/deactivate
    defaults: { _controller: "OrionEventBundle:Admin_Type:deactivate" }
   
admin_type_search:
    path: /search
    defaults: { _controller: "OrionEventBundle:Admin_Type:search" }
