orion_forum_homepage:
    path:     /
    defaults: { _controller: OrionForumBundle:Default:index }
orion_forum_category_routing:
    resource: "@OrionForumBundle/Controller/CategoryController.php"
    prefix:   /forum
    type:     annotation

orion_forum_forum_routing:
    resource: "@OrionForumBundle/Controller/ForumController.php"
    prefix:   /forum
    type:     annotation

orion_forum_topic_routing:
    resource: "@OrionForumBundle/Controller/TopicController.php"
    prefix:   /forum
    type:     annotation

orion_forum__post_routing:
    resource: "@OrionForumBundle/Controller/PostController.php"
    prefix:   /forum
    type:     annotation

orion_forum_label_routing:
    resource: "@OrionForumBundle/Controller/LabelController.php"
    prefix:   /forum
    type:     annotation

orion_forum_admin_routing:
    resource: "@OrionForumBundle/Controller/AdminController.php"
    prefix:   /forum
    type:     annotation
