services:
    topic.listener.updatelastpost:
        class: Orion\ForumBundle\EventListener\UpdateTopic
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postRemove }

    orion.forum.pagin:
            class: Orion\ForumBundle\Component\Pagin
            arguments:
                - '@request_stack'
                - '@knp_paginator'
                - '%orion_forum.pagination%'
                - '%orion_forum.pagination.pagename%'

    orion.forum.security.category_voter:
        class: Orion\ForumBundle\Security\CategoryVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    orion.forum.security.forum_voter:
        class: Orion\ForumBundle\Security\ForumVoter
        arguments: 
            - '@security.access.decision_manager'
        public: false
        tags:
            - { name: security.voter }

    orion.forum.security.topic_voter:
        class: Orion\ForumBundle\Security\TopicVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    orion.forum.security.post_voter:
        class: Orion\ForumBundle\Security\PostVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    orion.forum.twig_extension:
        class: Orion\ForumBundle\Twig\DForumExtension
        arguments: 
            - '@doctrine.orm.entity_manager'
            - '@router'
            - '%orion_forum.pagination%'
        public: false
        tags:
            - { name: twig.extension }

    orion.forum.form.remove.forum:
        class: Orion\ForumBundle\Form\Type\Remover\RemoveForumType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    orion.forum.form.remove.category:
        class: Orion\ForumBundle\Form\Type\Remover\RemoveCategoryType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    forum.listener.dropauser:
        class: Orion\ForumBundle\EventListener\ForumListener
        tags:
            - { name: doctrine.event_listener, event: preRemove }
